name: TREES
channels:
  - defaults
dependencies:
  - libgfortran=5.0.0
  - readline=8.2
  - pip=23.1.2
  - scikit-learn=1.2.2
  - packaging=23.0
  - blas=1.0
  - numpy-base=1.25.0
  - libgfortran5=11.3.0
  - hdf5=1.12.1
  - idna=3.4
  - requests=2.29.0
  - appdirs=1.4.4
  - h5py=3.7.0
  - libssh2=1.10.0
  - python=3.11.4
  - urllib3=1.26.16
  - tenacity=8.2.2
  - charset-normalizer=2.0.4
  - libnghttp2=1.52.0
  - ca-certificates
  - bzip2=1.0.8
  - joblib=1.2.0
  - libcxx=14.0.6
  - libopenblas=0.3.21
  - pyopenssl=23.0.0
  - scipy=1.10.1
  - libcurl=8.1.1
  - llvm-openmp=14.0.6
  - zlib=1.2.13
  - numpy=1.25.0
  - tzdata=2023c
  - libffi=3.4.4
  - pooch=1.4.0
  - pysocks=1.7.1
  - xz=5.4.2
  - krb5=1.20.1
  - sqlite=3.41.2
  - openssl
  - brotlipy=0.7.0
  - c-ares=1.19.0
  - libev=4.33
  - setuptools=67.8.0
  - threadpoolctl=2.2.0
  - libedit=3.1.20221030
  - pycparser=2.21
  - tk=8.6.12
  - certifi
  - plotly=5.9.0
  - cffi=1.15.1
  - ncurses=6.4
  - wheel=0.38.4
  - cryptography=39.0.1
  - ipykernel
